stages:         
  - image-builder
  - push-to-dockerhub
  - deploy-to-dev

build-image-job:       
  stage: image-builder
  script:
    - docker build -t dev-srv-image .
    - docker images
    - echo "ok"

push-image-job:   
  stage: push-to-dockerhub    
  script:
   - docker tag dev-srv-image $DKHUser/dev-srv-image:$CI_COMMIT_SHORT_SHA
   - echo $DKHPsswd | docker login -u $DKHUser --password-stdin
   - docker push $DKHUser/dev-srv-image:$CI_COMMIT_SHORT_SHA

deploy-job:   
  stage: deploy-to-dev   
  script:
    - docker rm -f dev-srv 
    - docker run --name dev-srv -d -p 8080:5000 $DKHUser/dev-srv-image:$CI_COMMIT_SHORT_SHA
    - echo "C'est fini bordel de merde"
